[parity]
chain = "utils/genesis_authority.json"
base-path = "/societhy/.parity"

[rpc]
interface = "127.0.0.1"
hosts = ["all"]
apis = ["web3","eth","net","parity","traces","rpc","personal","signer"]

[account]
unlock = ["0x5d8d77e9933279d6896eba0c08a3ec658168fcdb"]
password = ["/societhy/utils/passwordkey"]

[mining]
engine_signer = "0x5d8d77e9933279d6896eba0c08a3ec658168fcdb"
reseal_on_txs = "none"
usd_per_tx = "0"